version: '3.4'
services:
  chat.app:
    build: ./src/chat-app
    ports:
     - "3000:3000"
    depends_on:
     - chatserver.api
    environment:
     - REACT_APP_CHAT_URL=http://localhost:5000/api
     - REACT_APP_CHAT_WS=ws://localhost:5000/ws
     - CHOKIDAR_USEPOLLING=true
    volumes:
     - './src/chat-app:/app'
  chatserver.api:
    build: ./src/ChatServer
    restart: on-failure
    ports:
     - "5000:5000"
     - "10222:22"
    depends_on:
     - rabbitmq
     - redis
    environment:
     - ASPNETCORE_URLS=http://0.0.0.0:5000
     - ASPNETCORE_ENVIRONMENT=Docker
     - DOTNET_RUNNING_IN_CONTAINER=true
     - Connections__Redis=redis
     - Connections__RabbitMQ=rabbitmq
     - OwnHost=http://chatserver.api:5000
    volumes:
     - './src/ChatServer:/app'
  chatbroker.api:
    build: ./src/ChatBroker
    restart: on-failure
    ports:
     - "5550:5550"
     - "10223:22"
    depends_on:
     - redis
     - rabbitmq
    environment:
     - ASPNETCORE_URLS=http://0.0.0.0:5550
     - ASPNETCORE_ENVIRONMENT=Docker
     - DOTNET_RUNNING_IN_CONTAINER=true
     - Connections__Redis=redis
     - Connections__RabbitMQ=rabbitmq
     - OwnHost=http://chatbroker.api:5550
    volumes:
     - './src/ChatBroker:/app'
  redis:
    image: "redis:latest"
    ports:
     - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 2s
      retries: 10
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=chatserver
    #volumes:
    #  - './data/test/postgres:/var/lib/postgresql/data'
    ports:
     - "5432:5432"
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
     - "5672:5672"    
     - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 20s