version: '3'
services:
  chatserver.api:
    build: ./src/ChatServer
    ports:
     - "5000:5000"
    depends_on:
     - redis
     - rabbitmq
  chatbroker.api:
    build: ./src/ChatBroker
    ports:
     - "5550:5550"
    depends_on:
     - redis
     - rabbitmq
  redis.db:
    image: "redis:latest"
  postgres.db:
    image: "postgres:latest"
  rabbitmq.bus:
    image: "rabbitmq:management"