version: '3'
services:
  web:
    build: ./ChatServer
    ports:
     - "5000:5000"
    depends_on:
     - redis
     - rabbitmq
  redis:
    image: "redis:latest"
  postgres:
    image: "postgres:latest"
  rabbitmq:
    image: "rabbitmq:management"